### ISSUE TITLE
Crear un nuevo archivo para clientes

### ISSUE THREAD

**Issue by mackpipe** [mackpipe/curso_drupal#1]
## Tarea a realizar
- Crear un archivo nuevo llamado clientes.html en su proyecto local
- Poner un h1 con el titulo "CLIENTES"
- Subir al repositorio

**Comment by Cabiltred** [comment]
Se realiza creación de archivo clientes
![image](https://user-images.githubusercontent.com/75544836/118709987-52d3bf00-b7e3-11eb-9773-e413646f2876.png)

**Comment by mackpipe** [comment]
Excelente
