### ISSUE TITLE
1002 - Crear la pagina de servicios

### ISSUE THREAD

**Issue by mackpipe** [mackpipe/curso_drupal#10]
## Tare a realizar
- Crear el archivo de servicios.html
- En el archivo poner un titulo llamado "Mis servicios"
- Crear una lista de productos como la siguiente : Consultoria, Diseño, Desarrollo, analisis Etc 

NOTA: Se debe trabajar en una rama independiente, a partir de la rama develop

## Sugerencia para la rama
- La rama debe llamarse 1002-issue
- El commit debe ser construido de la siguiente manera
´ git commit -m ":emoji: #1002 El mensaje del commit"´
- Luego de esto, hacer el pull request a la rama develop

**Comment by Cabiltred** [comment]
Se crea el archivo de servicios.html, se agrega titulo y lista de productos solicitados. Se cumple con los requisitos de la rama, se adjunta evidencia del issue

![image](https://user-images.githubusercontent.com/75544836/119010789-08288300-b95a-11eb-9589-ce71f190e61f.png)

**Comment by mackpipe** [comment]
Listo, se aprueba
