### ISSUE TITLE
1003-Crear la pagina de testimonio

### ISSUE THREAD

**Issue by mackpipe** [mackpipe/curso_drupal#17]
## Tareas a realizar
- Crear pagina de testimonio
- Adicionar dos testimonios

## Nota
- Cada testimonio debe tener, titulo, Texto e imagen

**Comment by Cabiltred** [comment]
Se crea pagina de Testimonios y carpeta de imagenes para los dos testimonios

![image](https://user-images.githubusercontent.com/75544836/119056076-b39ffa80-b98f-11eb-9c00-dd611defe1d7.png)

**Comment by mackpipe** [comment]
perfecto
