### ISSUE TITLE
1004-Crear la pagina de contactenos

### ISSUE THREAD

**Issue by mackpipe** [mackpipe/curso_drupal#18]
## Tareas a realizar
# Crear pagian de contactenos, la cual tiene los siguientes campos
- Nombre
- Asunto
- Correo
- Celular
- Boton de enviar

**Comment by leyla68** [comment]
Se realizo la creación de la pagina contactenos, con los campos solicitados:

![image](https://user-images.githubusercontent.com/84405166/119053846-49398b00-b98c-11eb-9416-04f8424996fd.png)

**Comment by mackpipe** [comment]
Perfecto
