### ISSUE TITLE
Adicionar un h2 en el archivo de clientes

### ISSUE THREAD

**Issue by mackpipe** [mackpipe/curso_drupal#2]
## Tarea a realizar
- En el archivo de clientes.html, adicionar un h2 que diga "Listado de clientes"

**Comment by leyla68** [comment]
Se agrego Listado de Clientes
![image](https://user-images.githubusercontent.com/84405166/118715550-5f5b1600-b7e9-11eb-9e9d-29bab2b8c3ac.png)

**Comment by mackpipe** [comment]
excelente
