### ISSUE TITLE
Crear h3 en clientes

### ISSUE THREAD

**Issue by mackpipe** [mackpipe/curso_drupal#3]
## Tarea a realizar
-Abrir el archivo de cliente y si ya contiene un h2, entonces poner un h3 que diga "Los Destacados"

**Comment by Cabiltred** [comment]
Se agrega linea Los Destacados con titulo h3
![image](https://user-images.githubusercontent.com/75544836/118729802-28dac680-b7fc-11eb-82f9-88f7e59da728.png)
