### ISSUE TITLE
1. Crear un archivo nuevo para escribir un poema

### ISSUE THREAD

**Issue by mackpipe** [mackpipe/curso_drupal#4]
## Tarea a realizar
- Crear un archivo llamado `poema.html`
- Dentro del archivo dejar la estructura HTML5 mínima básica de una pagina
-  Crear un titulo que diga "Primera estrofa"
-  Luego del titulo crear un párrafo y utilizar texto de prueba (Lorem Ipsum)

**Comment by Cabiltred** [comment]
Se crea archivo poema. html con estructura basica HTML5, se crea titulo para la primera estrofa y se adiciona en parrafo un texto lorem ipsum 

![image](https://user-images.githubusercontent.com/75544836/118840187-c4b41300-b88c-11eb-9304-ab6ae78e5a96.png)
