### ISSUE TITLE
2. Crear la segunda estrofa del poema

### ISSUE THREAD

**Issue by mackpipe** [mackpipe/curso_drupal#5]
## Tarea a realizar
- Editar el archivo poema.html
- Crear el titulo para la segunda estrofa del poema, basándose en el titulo de la primer estrofa
- Crear un párrafo para la segunda estrofa usando texto de prueba ( lorem ipsum)

**Comment by leyla68** [comment]
Se realizo creación de la segunda Estrofa

![image](https://user-images.githubusercontent.com/84405166/118840030-a3ebbd80-b88c-11eb-984a-db191f662dcb.png)
