### ISSUE TITLE
3. Crear la tercera estrofa del poema

### ISSUE THREAD

**Issue by mackpipe** [mackpipe/curso_drupal#6]
## Tarea a realizar
- Editar el archivo poema.html
- Crear el titulo para la tercera estrofa del poema
- Crear un párrafo para la tercera estrofa usando texto de prueba ( lorem ipsum)

**Comment by Cabiltred** [comment]
Se adiciona la tercera estrofa al poema
![image](https://user-images.githubusercontent.com/75544836/118838780-94b84000-b88b-11eb-890b-d93400afa2ff.png)
