### ISSUE TITLE
1001 - Crear archivo de productos

### ISSUE THREAD

**Issue by mackpipe** [mackpipe/curso_drupal#9]
## Tare a realizar
- Crear el archivo de productos.html
- En el archivo poner un titulo llamado "Mis productos"
-  Crear una lista de productos como la siguiente :  Para, Yuca, Platano, Zaahoria etc

NOTA:  Se debe trabajar en una rama independiente, a partir de la rama **develop**

## Sugerencia para la rama
- La rama debe llamarse 1001-issue
- El commit debe ser construido de la siguiente manera  
  ´ git commit -m ":emoji: #1001 El mensaje del commit"´
- Luego de esto, hacer el pull request a la rama develop

**Comment by leyla68** [comment]
Se realiza la creación del nuevo producto en el archivo productos.html

![image](https://user-images.githubusercontent.com/84405166/119020627-14194280-b964-11eb-88cf-1724a2f713bb.png)

**Comment by mackpipe** [comment]
Se aprueba
